/// Integration tests comparing Rust output against C++ reference output.
/// Reference data was generated by the original C++ Kraken 2 tools.
use std::fs;
use std::path::PathBuf;

fn test_data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("kraken2/data")
}

fn reference_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/reference")
}

/// Test: classify a single sequence using the reference database
/// and compare output line-for-line against C++ reference.
#[test]
fn test_classify_covid_matches_reference() {
    let ref_dir = reference_dir();
    let hash_file = ref_dir.join("hash.k2d");
    let taxo_file = ref_dir.join("taxo.k2d");
    let opts_file = ref_dir.join("opts.k2d");
    let input_file = test_data_dir().join("COVID_19.fa");
    let reference_output = ref_dir.join("classify_covid.txt");

    // Skip if reference data not available
    if !hash_file.exists() || !reference_output.exists() {
        eprintln!("Skipping test: reference data not available");
        return;
    }

    let tmp_dir = tempfile::tempdir().unwrap();
    let output_file = tmp_dir.path().join("kraken_output.txt");

    let opts = kraken2_pure_rs::classify::ClassifyOptions::default();

    let result = kraken2_pure_rs::classify::run_classify(
        &[input_file.to_str().unwrap().to_string()],
        hash_file.to_str().unwrap(),
        taxo_file.to_str().unwrap(),
        opts_file.to_str().unwrap(),
        &opts,
        Some(output_file.to_str().unwrap()),
        None,
        None,
        None,
    );

    let stats = result.expect("Classification failed");
    assert_eq!(stats.total_sequences, 1);
    assert_eq!(stats.total_classified, 1);

    // Compare output
    let rust_output = fs::read_to_string(&output_file).unwrap();
    let ref_output = fs::read_to_string(&reference_output).unwrap();

    let rust_lines: Vec<&str> = rust_output.trim().lines().collect();
    let ref_lines: Vec<&str> = ref_output.trim().lines().collect();

    assert_eq!(
        rust_lines.len(),
        ref_lines.len(),
        "Line count mismatch: Rust={}, Ref={}",
        rust_lines.len(),
        ref_lines.len()
    );

    for (i, (rust_line, ref_line)) in rust_lines.iter().zip(ref_lines.iter()).enumerate() {
        assert_eq!(
            rust_line,
            ref_line,
            "Line {} differs:\nRust: {}\nRef:  {}",
            i + 1,
            rust_line,
            ref_line
        );
    }
}

/// Test: classify all test sequences and compare against C++ reference.
#[test]
fn test_classify_all_matches_reference() {
    let ref_dir = reference_dir();
    let hash_file = ref_dir.join("hash.k2d");
    let taxo_file = ref_dir.join("taxo.k2d");
    let opts_file = ref_dir.join("opts.k2d");
    let reference_output = ref_dir.join("classify_all.txt");

    if !hash_file.exists() || !reference_output.exists() {
        eprintln!("Skipping test: reference data not available");
        return;
    }

    // Collect all FASTA files in the same order as `cat kraken2/data/*.fa`
    let data_dir = test_data_dir();
    let mut fasta_files: Vec<String> = fs::read_dir(&data_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|e| e == "fa").unwrap_or(false))
        .map(|p| p.to_str().unwrap().to_string())
        .collect();
    fasta_files.sort(); // Shell glob order is sorted

    let tmp_dir = tempfile::tempdir().unwrap();
    let output_file = tmp_dir.path().join("kraken_output.txt");

    let opts = kraken2_pure_rs::classify::ClassifyOptions::default();

    let result = kraken2_pure_rs::classify::run_classify(
        &fasta_files,
        hash_file.to_str().unwrap(),
        taxo_file.to_str().unwrap(),
        opts_file.to_str().unwrap(),
        &opts,
        Some(output_file.to_str().unwrap()),
        None,
        None,
        None,
    );

    let stats = result.expect("Classification failed");
    assert_eq!(stats.total_sequences, 38, "Expected 38 sequences");

    // Compare output line by line
    let rust_output = fs::read_to_string(&output_file).unwrap();
    let ref_output = fs::read_to_string(&reference_output).unwrap();

    let rust_lines: Vec<&str> = rust_output.trim().lines().collect();
    let ref_lines: Vec<&str> = ref_output.trim().lines().collect();

    assert_eq!(
        rust_lines.len(),
        ref_lines.len(),
        "Line count mismatch: Rust={}, Ref={}",
        rust_lines.len(),
        ref_lines.len()
    );

    // Compare first 5 fields (C/U, header, taxid, len, hitlist)
    let mut mismatches = Vec::new();
    for (i, (rust_line, ref_line)) in rust_lines.iter().zip(ref_lines.iter()).enumerate() {
        if rust_line != ref_line {
            mismatches.push(format!(
                "Line {} differs:\n  Rust: {}\n  Ref:  {}",
                i + 1,
                &rust_line[..rust_line.len().min(120)],
                &ref_line[..ref_line.len().min(120)],
            ));
        }
    }

    if !mismatches.is_empty() {
        panic!(
            "{} of {} lines differ:\n{}",
            mismatches.len(),
            ref_lines.len(),
            mismatches.join("\n")
        );
    }
}

/// Test: load taxonomy from reference binary and verify node count.
#[test]
fn test_load_reference_taxonomy() {
    let ref_dir = reference_dir();
    let taxo_file = ref_dir.join("taxo.k2d");

    if !taxo_file.exists() {
        eprintln!("Skipping test: reference data not available");
        return;
    }

    let mut taxonomy =
        kraken2_pure_rs::taxonomy::Taxonomy::from_file(taxo_file.to_str().unwrap(), false).unwrap();
    taxonomy.generate_external_to_internal_id_map();

    // 38 sequences + ancestors + root = 40 nodes (39 marked + node 0)
    assert_eq!(
        taxonomy.node_count(),
        40,
        "Expected 40 taxonomy nodes, got {}",
        taxonomy.node_count()
    );

    // Root node should be internal ID 1
    assert_eq!(taxonomy.node(1).external_id, 1);

    // Check a known taxid
    let covid_internal = taxonomy.get_internal_id(2697049);
    assert!(covid_internal > 0, "COVID taxid not found");
    assert_eq!(taxonomy.node(covid_internal).external_id, 2697049);
}

/// Test: load reference hash table and verify properties.
#[test]
fn test_load_reference_hash_table() {
    let ref_dir = reference_dir();
    let hash_file = ref_dir.join("hash.k2d");

    if !hash_file.exists() {
        eprintln!("Skipping test: reference data not available");
        return;
    }

    let hash = kraken2_pure_rs::compact_hash::CompactHashTable::from_file(
        hash_file.to_str().unwrap(),
        false,
    )
    .unwrap();

    assert_eq!(hash.capacity(), 92526);
    assert!(hash.size() > 0, "Hash table should not be empty");
    assert_eq!(hash.key_bits() + hash.value_bits(), 32);
    assert!(hash.occupancy() > 0.0 && hash.occupancy() < 1.0);
}

/// Test: read IndexOptions from reference opts.k2d.
#[test]
fn test_read_reference_index_options() {
    let ref_dir = reference_dir();
    let opts_file = ref_dir.join("opts.k2d");

    if !opts_file.exists() {
        eprintln!("Skipping test: reference data not available");
        return;
    }

    let opts = kraken2_pure_rs::types::IndexOptions::read_from_file(opts_file.to_str().unwrap())
        .expect("Failed to read index options");

    assert_eq!(opts.k, 35);
    assert_eq!(opts.l, 31);
    assert!(opts.dna_db);
    assert_eq!(opts.revcom_version, 1);
}

/// Test: classify gzip-compressed input and verify output matches uncompressed.
#[test]
fn test_classify_gzip_input() {
    let ref_dir = reference_dir();
    let hash_file = ref_dir.join("hash.k2d");
    let taxo_file = ref_dir.join("taxo.k2d");
    let opts_file = ref_dir.join("opts.k2d");
    let input_file = test_data_dir().join("COVID_19.fa");
    let reference_output = ref_dir.join("classify_covid.txt");

    if !hash_file.exists() || !reference_output.exists() {
        return;
    }

    // Create gzip compressed input
    let tmp_dir = tempfile::tempdir().unwrap();
    let gz_input = tmp_dir.path().join("input.fa.gz");
    let input_data = fs::read(&input_file).unwrap();
    let gz_file = std::fs::File::create(&gz_input).unwrap();
    let mut encoder = flate2::write::GzEncoder::new(gz_file, flate2::Compression::default());
    std::io::Write::write_all(&mut encoder, &input_data).unwrap();
    encoder.finish().unwrap();

    let output_file = tmp_dir.path().join("kraken_output.txt");
    let opts = kraken2_pure_rs::classify::ClassifyOptions::default();

    let result = kraken2_pure_rs::classify::run_classify(
        &[gz_input.to_str().unwrap().to_string()],
        hash_file.to_str().unwrap(),
        taxo_file.to_str().unwrap(),
        opts_file.to_str().unwrap(),
        &opts,
        Some(output_file.to_str().unwrap()),
        None,
        None,
        None,
    )
    .unwrap();

    assert_eq!(result.total_sequences, 1);
    assert_eq!(result.total_classified, 1);

    let rust_output = fs::read_to_string(&output_file).unwrap();
    let ref_output = fs::read_to_string(&reference_output).unwrap();
    assert_eq!(
        rust_output.trim(),
        ref_output.trim(),
        "Gzip input produced different output than uncompressed"
    );
}
